package cui.edu.BEAN;

// Generated 2015-4-10 13:51:26 by Hibernate Tools 3.4.0.CR1

/**
 * BasicMessage generated by hbm2java
 */
public class BasicMessage implements java.io.Serializable {

	private int id;
	private String name;
	private Integer age;
	private String sex;
	private Integer dept;
	private Integer headship;

	public BasicMessage() {
	}

	public BasicMessage(int id) {
		this.id = id;
	}

	public BasicMessage(int id, String name, Integer age, String sex,
			Integer dept, Integer headship) {
		this.id = id;
		this.name = name;
		this.age = age;
		this.sex = sex;
		this.dept = dept;
		this.headship = headship;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getDept() {
		return this.dept;
	}

	public void setDept(Integer dept) {
		this.dept = dept;
	}

	public Integer getHeadship() {
		return this.headship;
	}

	public void setHeadship(Integer headship) {
		this.headship = headship;
	}

}
