package cui.edu.BEAN;

// Generated 2015-4-10 13:51:26 by Hibernate Tools 3.4.0.CR1

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private int id;
	private Integer hid;
	private String contact;
	private String officePhone;
	private String fax;
	private String email;
	private String faddress;

	public Contact() {
	}

	public Contact(int id, String fax) {
		this.id = id;
		this.fax = fax;
	}

	public Contact(int id, Integer hid, String contact, String officePhone,
			String fax, String email, String faddress) {
		this.id = id;
		this.hid = hid;
		this.contact = contact;
		this.officePhone = officePhone;
		this.fax = fax;
		this.email = email;
		this.faddress = faddress;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getHid() {
		return this.hid;
	}

	public void setHid(Integer hid) {
		this.hid = hid;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getOfficePhone() {
		return this.officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFaddress() {
		return this.faddress;
	}

	public void setFaddress(String faddress) {
		this.faddress = faddress;
	}

}
