package cui.edu.BEAN;

// Generated 2015-4-10 13:51:26 by Hibernate Tools 3.4.0.CR1

/**
 * Depot generated by hbm2java
 */
public class Depot implements java.io.Serializable {

	private int id;
	private String manage;
	private String functional;

	public Depot() {
	}

	public Depot(int id) {
		this.id = id;
	}

	public Depot(int id, String manage, String functional) {
		this.id = id;
		this.manage = manage;
		this.functional = functional;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getManage() {
		return this.manage;
	}

	public void setManage(String manage) {
		this.manage = manage;
	}

	public String getFunctional() {
		return this.functional;
	}

	public void setFunctional(String functional) {
		this.functional = functional;
	}

}
