package cui.edu.BEAN;

// Generated 2015-4-10 13:51:26 by Hibernate Tools 3.4.0.CR1

/**
 * EmployeeId generated by hbm2java
 */
public class EmployeeId implements java.io.Serializable {

	private Integer id;
	private Integer did;
	private String ename;
	private String job;
	private Double laborage;
	private String phone;
	private String qqnumber;
	private String email;

	public EmployeeId() {
	}

	public EmployeeId(Integer id, Integer did, String ename, String job,
			Double laborage, String phone, String qqnumber, String email) {
		this.id = id;
		this.did = did;
		this.ename = ename;
		this.job = job;
		this.laborage = laborage;
		this.phone = phone;
		this.qqnumber = qqnumber;
		this.email = email;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public Double getLaborage() {
		return this.laborage;
	}

	public void setLaborage(Double laborage) {
		this.laborage = laborage;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getQqnumber() {
		return this.qqnumber;
	}

	public void setQqnumber(String qqnumber) {
		this.qqnumber = qqnumber;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeId))
			return false;
		EmployeeId castOther = (EmployeeId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getDid() == castOther.getDid()) || (this.getDid() != null
						&& castOther.getDid() != null && this.getDid().equals(
						castOther.getDid())))
				&& ((this.getEname() == castOther.getEname()) || (this
						.getEname() != null && castOther.getEname() != null && this
						.getEname().equals(castOther.getEname())))
				&& ((this.getJob() == castOther.getJob()) || (this.getJob() != null
						&& castOther.getJob() != null && this.getJob().equals(
						castOther.getJob())))
				&& ((this.getLaborage() == castOther.getLaborage()) || (this
						.getLaborage() != null
						&& castOther.getLaborage() != null && this
						.getLaborage().equals(castOther.getLaborage())))
				&& ((this.getPhone() == castOther.getPhone()) || (this
						.getPhone() != null && castOther.getPhone() != null && this
						.getPhone().equals(castOther.getPhone())))
				&& ((this.getQqnumber() == castOther.getQqnumber()) || (this
						.getQqnumber() != null
						&& castOther.getQqnumber() != null && this
						.getQqnumber().equals(castOther.getQqnumber())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getDid() == null ? 0 : this.getDid().hashCode());
		result = 37 * result
				+ (getEname() == null ? 0 : this.getEname().hashCode());
		result = 37 * result
				+ (getJob() == null ? 0 : this.getJob().hashCode());
		result = 37 * result
				+ (getLaborage() == null ? 0 : this.getLaborage().hashCode());
		result = 37 * result
				+ (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result
				+ (getQqnumber() == null ? 0 : this.getQqnumber().hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		return result;
	}

}
