package cui.edu.BEAN;

// Generated 2015-4-10 13:51:26 by Hibernate Tools 3.4.0.CR1

/**
 * JoinDepot generated by hbm2java
 */
public class JoinDepot implements java.io.Serializable {

	private int id;
	private String oid;
	private Integer did;
	private String wareName;
	private String joinTime;
	private Double weight;
	private String remark;

	public JoinDepot() {
	}

	public JoinDepot(int id) {
		this.id = id;
	}

	public JoinDepot(int id, String oid, Integer did, String wareName,
			String joinTime, Double weight, String remark) {
		this.id = id;
		this.oid = oid;
		this.did = did;
		this.wareName = wareName;
		this.joinTime = joinTime;
		this.weight = weight;
		this.remark = remark;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public String getWareName() {
		return this.wareName;
	}

	public void setWareName(String wareName) {
		this.wareName = wareName;
	}

	public String getJoinTime() {
		return this.joinTime;
	}

	public void setJoinTime(String joinTime) {
		this.joinTime = joinTime;
	}

	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
