package cui.edu.BEAN;

// Generated 2015-4-10 13:51:26 by Hibernate Tools 3.4.0.CR1

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private int id;
	private String sname;
	private String orderId;
	private String consignmentDate;
	private String baleName;
	private String count;
	private Double money;

	public Stock() {
	}

	public Stock(int id) {
		this.id = id;
	}

	public Stock(int id, String sname, String orderId, String consignmentDate,
			String baleName, String count, Double money) {
		this.id = id;
		this.sname = sname;
		this.orderId = orderId;
		this.consignmentDate = consignmentDate;
		this.baleName = baleName;
		this.count = count;
		this.money = money;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getConsignmentDate() {
		return this.consignmentDate;
	}

	public void setConsignmentDate(String consignmentDate) {
		this.consignmentDate = consignmentDate;
	}

	public String getBaleName() {
		return this.baleName;
	}

	public void setBaleName(String baleName) {
		this.baleName = baleName;
	}

	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public Double getMoney() {
		return this.money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

}
