package cuit.edu.BEAN;

// Generated 2015-4-13 10:16:12 by Hibernate Tools 3.4.0.CR1

/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private int id;
	private String dname;
	private String principal;
	private String bewrite;

	public Dept() {
	}

	public Dept(int id) {
		this.id = id;
	}

	public Dept(int id, String dname, String principal, String bewrite) {
		this.id = id;
		this.dname = dname;
		this.principal = principal;
		this.bewrite = bewrite;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	public String getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public String getBewrite() {
		return this.bewrite;
	}

	public void setBewrite(String bewrite) {
		this.bewrite = bewrite;
	}

}
