package cuit.edu.BEAN;

// Generated 2015-4-13 10:16:12 by Hibernate Tools 3.4.0.CR1

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private EmployeeId id;

	public Employee() {
	}

	public Employee(EmployeeId id) {
		this.id = id;
	}

	public EmployeeId getId() {
		return this.id;
	}

	public void setId(EmployeeId id) {
		this.id = id;
	}

}
