package cuit.edu.BEAN;

// Generated 2015-4-13 10:16:12 by Hibernate Tools 3.4.0.CR1

/**
 * Sell generated by hbm2java
 */
public class Sell implements java.io.Serializable {

	private int id;
	private String sellName;
	private String address;
	private String linkman;
	private String linkPhone;
	private String faxNum;
	private String postNum;
	private String bankNum;
	private String netAddress;
	private String emaillAddress;
	private String remark;

	public Sell() {
	}

	public Sell(int id) {
		this.id = id;
	}

	public Sell(int id, String sellName, String address, String linkman,
			String linkPhone, String faxNum, String postNum, String bankNum,
			String netAddress, String emaillAddress, String remark) {
		this.id = id;
		this.sellName = sellName;
		this.address = address;
		this.linkman = linkman;
		this.linkPhone = linkPhone;
		this.faxNum = faxNum;
		this.postNum = postNum;
		this.bankNum = bankNum;
		this.netAddress = netAddress;
		this.emaillAddress = emaillAddress;
		this.remark = remark;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getSellName() {
		return this.sellName;
	}

	public void setSellName(String sellName) {
		this.sellName = sellName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getLinkPhone() {
		return this.linkPhone;
	}

	public void setLinkPhone(String linkPhone) {
		this.linkPhone = linkPhone;
	}

	public String getFaxNum() {
		return this.faxNum;
	}

	public void setFaxNum(String faxNum) {
		this.faxNum = faxNum;
	}

	public String getPostNum() {
		return this.postNum;
	}

	public void setPostNum(String postNum) {
		this.postNum = postNum;
	}

	public String getBankNum() {
		return this.bankNum;
	}

	public void setBankNum(String bankNum) {
		this.bankNum = bankNum;
	}

	public String getNetAddress() {
		return this.netAddress;
	}

	public void setNetAddress(String netAddress) {
		this.netAddress = netAddress;
	}

	public String getEmaillAddress() {
		return this.emaillAddress;
	}

	public void setEmaillAddress(String emaillAddress) {
		this.emaillAddress = emaillAddress;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
