package cuit.edu.BEAN;

// Generated 2015-4-13 10:16:12 by Hibernate Tools 3.4.0.CR1

/**
 * Ware generated by hbm2java
 */
public class Ware implements java.io.Serializable {

	private int id;
	private String wareName;
	private String warBewrite;
	private String spec;
	private Double stockPrice;
	private Double retailPrice;
	private Double associatorPrice;

	public Ware() {
	}

	public Ware(int id) {
		this.id = id;
	}

	public Ware(int id, String wareName, String warBewrite, String spec,
			Double stockPrice, Double retailPrice, Double associatorPrice) {
		this.id = id;
		this.wareName = wareName;
		this.warBewrite = warBewrite;
		this.spec = spec;
		this.stockPrice = stockPrice;
		this.retailPrice = retailPrice;
		this.associatorPrice = associatorPrice;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getWareName() {
		return this.wareName;
	}

	public void setWareName(String wareName) {
		this.wareName = wareName;
	}

	public String getWarBewrite() {
		return this.warBewrite;
	}

	public void setWarBewrite(String warBewrite) {
		this.warBewrite = warBewrite;
	}

	public String getSpec() {
		return this.spec;
	}

	public void setSpec(String spec) {
		this.spec = spec;
	}

	public Double getStockPrice() {
		return this.stockPrice;
	}

	public void setStockPrice(Double stockPrice) {
		this.stockPrice = stockPrice;
	}

	public Double getRetailPrice() {
		return this.retailPrice;
	}

	public void setRetailPrice(Double retailPrice) {
		this.retailPrice = retailPrice;
	}

	public Double getAssociatorPrice() {
		return this.associatorPrice;
	}

	public void setAssociatorPrice(Double associatorPrice) {
		this.associatorPrice = associatorPrice;
	}

}
